module.exports = {
	JUMPING: -1,
	FALLING: 1,
	IDLE: 0,
	RIGHT: 1,
	LEFT: -1,
	tileSize:16,
	mapLeft:1,
	mapTop:2,
	mapRight:4,
	mapBottom:8,
	allowFlipX:1,
	allowFlipY:2,
	allowRotate:4,
	usableRooms:9,
	roomSize:10,
	miniMapSize:16,
	segmentsPerRoom:1,
	room2:"r2",
	room1:"r1",
	mapX:"x",
	mapY:"y",
	mapW:"mw",
	mapH:"mh",
	mapColor:"c",
	currentRegion:"cr",
	regions:"r",
	region:"r",
	specialType:"s",
	startPositionX:"sx",
	startPositionY:"sy",
	startRoom:"sr",
	visited:"v",
	doors:"d",
	doorType:"dt",
	background:"bg",
	border:"bd",
	other:"o",
	lock:"l",
	frontiers:"f",
	xDirection:"xd",
	yDirection:"yd",
	xAccel:"xa",
	yAccel:"ya",
	maxAccel:"ma",
	jumpForce:"jf",
	jumpHeight:"jh",
	jumpStart:"js",
	jumping:"j",
	jumpsUsed:"ju",
	heightTraveled:"ht",
	maxJumps:"mj",
	angle:"a",
	health:"ῼ",
	doorCooldown:"dc",
	maxHealth:"mῼ"
};